import { Roboto } from "next/font/google";

import "./globals.css";
import TheHeader from "@/components/theHeader/theHeader";

const roboto = Roboto({ weight: ["300", "400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <header>
          <TheHeader />
        </header>
        {children}
      </body>
    </html>
  );
}
